### ISSUE TITLE
While using animated ores with frames and nautilus 3d, the ores appear with copper ore texture mixed.

### ISSUE THREAD

**Issue by Kloytz** [giteczek/Aminated-Ore-Frame#2]
![2024-09-12_19 04 27](https://github.com/user-attachments/assets/5b4d9ca8-b033-4896-acb5-cb5e82526c59)

**Comment by raspberrygitq** [comment]
Hi, I can't reproduce your issue. Although I downloaded “Nautilus 3D” and “Animated Ores with Frames” and selected so that “Animated Ores with Frames” is above “Nautilus 3D” when loading the resource pack. These resource packs are not compatible. They don't even display the ore frames in my resource pack. In the sense they display, but in the form of an item in the hand.

![image](https://github.com/user-attachments/assets/bc5af775-f94d-445b-995f-5ace865987b4)
![image](https://github.com/user-attachments/assets/0ec6ae04-5011-4eed-aeff-685dc3c0ddfb)
