### ISSUE TITLE
Typo in pack name

### ISSUE THREAD

**Issue by TsengFayt** [giteczek/Aminated-Ore-Frame#3]
![image](https://github.com/user-attachments/assets/bba2a59b-39d4-4be5-a157-3b28a1bdd7ad)

As pictured, the pack name is misspelled as Aminated instead of Animated on the .zip that gets downloaded through Modrinth. Easy fix, but I thought it would be worth mentioning.

It's also incorrect above in the actual github directory.

**Comment by raspberrygitq** [comment]
> As pictured, the pack name is misspelled as Aminated instead of Animated on the .zip that gets downloaded through Modrinth. Easy fix, but I thought it would be worth mentioning.

This is just a visual error, it does not affect the operation of the resource pack. ~~I have a scheduled release only when version 1.21.4 is revealed. I will not specifically resubmit the project through a visual error.~~ IMPROVEMENT: However, I will resend the project file, because I chose the wrong branch, instead of `stable` I chose `dev`.

> It's also incorrect above in the actual github directory.

Not only the folder, but the repository had the wrong project name. It has been corrected.

Thank you for your report!
